snapshot:
  target:
    entity:
      integration: teufel_raumfeld
      domain: media_player
restore:
  target:
    entity:
      integration: teufel_raumfeld
      domain: media_player
group:
  fields:
    room_names:
      required: true
      description: List of room names that will be grouped together. At least one room
        must be specified
      example: "[ 'Kitchen', 'Living room' ]"
abs_volume_set:
  target:
    entity:
      integration: teufel_raumfeld
      domain: media_player
  fields:
    volume_level:
      required: true
      description: Volume level to set.
      example: 42
      default: 30
      selector:
        number:
          min: 0
          max: 100
    rooms:
      description: Optional name(s) of rooms to set volume level on. If not set,volume
        is set to all rooms in the speaker group.
      example: "[ Kitchen, Playroom ]"
play_sound:
  target:
    entity:
      integration: teufel_raumfeld
      domain: media_player
  fields:
    sound:
      required: true
      selector:
        select:
          options:
            - Failure
            - Success
      description: Sound to play
      example: Success
      default: Success
add_room:
  target:
    entity:
      integration: teufel_raumfeld
      domain: media_player
  fields:
    room:
      required: true
      description: Name of the room to add to the speaker group.
      example: Movie room
    room_of_group:
      required: true
      description: Name of one room member of the speaker group.
      example: Movie room
drop_room:
  fields:
    room:
      required: true
      description: Name of the room to remove from a speaker group.
      example: Movie room
    room_of_group:
      description: Name of the speaker group to remove the room from.
      example: Ground floor
set_room_volume:
  target:
    entity:
      integration: teufel_raumfeld
      domain: media_player
  fields:
    room:
      required: true
      description: Name of the room to remove from a speaker group.
      example: Movie room
    volume:
      required: true
      description: Name of one room member of the speaker group. If provided, the room
        must be member of that group.
      example: "42"
      default: "20"
      selector:
        number:
          min: 0
          max: 100
